"""update_session_word_with_both_translations

Revision ID: 20a0a815a4d5
Revises: cb38ceacc54e
Create Date: 2025-12-28 12:44:50.900227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20a0a815a4d5'
down_revision: Union[str, Sequence[str], None] = 'cb38ceacc54e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Delete existing session_results data as the schema is changing significantly
    op.execute('DELETE FROM session_results')
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session_results', sa.Column('translation_from_id', sa.UUID(), nullable=False))
    op.add_column('session_results', sa.Column('translation_to_id', sa.UUID(), nullable=False))
    op.add_column('session_results', sa.Column('from_language', sa.String(), nullable=False))
    op.add_column('session_results', sa.Column('to_language', sa.String(), nullable=False))
    op.drop_constraint(op.f('session_results_translation_id_fkey'), 'session_results', type_='foreignkey')
    op.create_foreign_key(None, 'session_results', 'languages', ['from_language'], ['code'])
    op.create_foreign_key(None, 'session_results', 'languages', ['to_language'], ['code'])
    op.create_foreign_key(None, 'session_results', 'translations', ['translation_from_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'session_results', 'translations', ['translation_to_id'], ['id'], ondelete='CASCADE')
    op.drop_column('session_results', 'translation_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session_results', sa.Column('translation_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'session_results', type_='foreignkey')
    op.drop_constraint(None, 'session_results', type_='foreignkey')
    op.drop_constraint(None, 'session_results', type_='foreignkey')
    op.drop_constraint(None, 'session_results', type_='foreignkey')
    op.create_foreign_key(op.f('session_results_translation_id_fkey'), 'session_results', 'translations', ['translation_id'], ['id'], ondelete='CASCADE')
    op.drop_column('session_results', 'to_language')
    op.drop_column('session_results', 'from_language')
    op.drop_column('session_results', 'translation_to_id')
    op.drop_column('session_results', 'translation_from_id')
    # ### end Alembic commands ###
