"""add_user_language_preferences

Revision ID: 73ba77e48bf1
Revises: aa407446db42
Create Date: 2025-12-08 20:57:53.841788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73ba77e48bf1'
down_revision: Union[str, Sequence[str], None] = 'aa407446db42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('native_language', sa.String(), nullable=True))
    op.add_column('users', sa.Column('learning_languages', sa.ARRAY(sa.String()), nullable=True))
    op.create_foreign_key(None, 'users', 'languages', ['native_language'], ['code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'learning_languages')
    op.drop_column('users', 'native_language')
    # ### end Alembic commands ###
