"""empty message

Revision ID: cb38ceacc54e
Revises: 4bd8b90e60b9
Create Date: 2025-12-28 11:58:03.823471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb38ceacc54e'
down_revision: Union[str, Sequence[str], None] = '4bd8b90e60b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session_results', sa.Column('user_answer', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session_results', 'user_answer')
    # ### end Alembic commands ###
